#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    liftPot,        sensorPotentiometer)
#pragma config(Sensor, in2,    auton_select,   sensorPotentiometer)
#pragma config(Sensor, dgtl1,  sonarBack,      sensorSONAR_cm)
#pragma config(Sensor, dgtl3,  fieldColor,     sensorDigitalIn)
#pragma config(Sensor, dgtl4,  shaftEncoderLeftDrive, sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  shaftEncoderRightDrive, sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  lift_enc,       sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           rightIntake,   tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightFront,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightBack,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rightTopLift,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightBottomLift, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftTopLift,   tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port7,           leftBottomLift, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftFront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftBack,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          leftIntake,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Vex_Competition_Includes.c"

//#include "safety.c"			//DONT FORGET YOUR SAFETY GLASSES
#include "drive.c"
#include "lift.c"
#include "pidcontroller.c"
#include "intake.c"
//#include "debug.c"
#include "autonomous.c"

task usercontrol() {
	startTask(drive);
	startTask(lift);
	startTask(pidController);
	startTask(intake);
}
