#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    liftPot,        sensorPotentiometer)
#pragma config(Sensor, in2,    auton_select,   sensorPotentiometer)
#pragma config(Sensor, dgtl1,  pneumaticLock1, sensorDigitalOut)
#pragma config(Sensor, dgtl2,  pneumaticLock2, sensorDigitalOut)
#pragma config(Sensor, dgtl9,  ,               sensorTouch)
#pragma config(Sensor, I2C_1,  lift_enc,       sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           rightIntake,   tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port2,           rightFront,    tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port3,           rightBack,     tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port4,           rightTopLift,  tmotorVex393, openLoop)
#pragma config(Motor,  port5,           rightBottomLift, tmotorVex393, openLoop)
#pragma config(Motor,  port6,           leftTopLift,   tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port7,           leftBottomLift, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           leftFront,     tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port9,           leftBack,      tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port10,          leftIntake,    tmotorVex393HighSpeed, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Vex_Competition_Includes.c"

#include "safety.c"			//DONT FORGET YOUR SAFETY GLASSES
#include "drive.c"
#include "lift.c"
#include "pidcontroller.c"
#include "intake.c"
#include "pneumatics.c"
//#include "debug.c"
#include "autonomous.c"

task usercontrol() {
	StartTask(drive);
	StartTask(pneumatics);
	StartTask(lift);
	StartTask(pidController);
	StartTask(intake);
	StartTask(safety);
}
